chore: dev build flow

diff --git a/.github/workflows/dev-build.yml b/.github/workflows/dev-build.yml
--- a/.github/workflows/dev-build.yml
+++ b/.github/workflows/dev-build.yml
@@ -89,23 +89,23 @@ jobs:
             npm version $VER --no-git-tag-version
           fi
 
-      - name: Install dependencies
-        shell: bash
-        run: yarn install --immutable
+      # - name: Install dependencies
+      #   shell: bash
+      #   run: yarn install --immutable
 
-      - name: Build
-        run: yarn build:prod
+      # - name: Build
+      #   run: yarn build:prod
 
-      - name: Publish
-        run: |
-          # make sure we have .d.ts files in our package
-          DTS=`ls ./dist/** | grep d.ts | wc -l`
-          echo "# of *.d.ts files is $DTS"
-          if [[ $DTS -eq 0 ]]; then
-            echo "Missing *.d.ts files"
-            exit 1
-          fi
-          yarn publish ./dist
+      # - name: Publish
+      #   run: |
+      #     # make sure we have .d.ts files in our package
+      #     DTS=`ls ./dist/** | grep d.ts | wc -l`
+      #     echo "# of *.d.ts files is $DTS"
+      #     if [[ $DTS -eq 0 ]]; then
+      #       echo "Missing *.d.ts files"
+      #       exit 1
+      #     fi
+      #     yarn publish ./dist --ignore-scripts
 
       # # outro
       # - name: Add version value to env
